Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore.Data;
using BookStore.Data.Entities;
using BookStore.Services.Service.Interfaces;
using BookStore.Models;
using System.IO;
using System.Net.Http.Headers;
using NPOI.SS.Formula.Functions;
using Microsoft.Extensions.Logging;
using BookStore.Logger;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace BookStore.Controllers
{
    [Authorize(Roles = "admin, editor")]
    public class BooksController : Controller
    {
        private readonly IBookService _bookService;
        private readonly ICategoryService _categoryService;
        private readonly IAuthorService _authorService;
        private readonly IPublisherService _publisherService;
        private readonly ILogger<BooksController> _logger;

        public BooksController(
            IBookService bookService,
            ICategoryService categoryService,
            IAuthorService authorService,
            IPublisherService publisherService,
            ILogger<BooksController> logger
        )
        {
            _bookService = bookService;
            _categoryService = categoryService;
            _authorService = authorService;
            _publisherService = publisherService;
            _logger = logger;
        }


        // GET: Books
        public IActionResult Index()
        {
            var bookList = _bookService.GetAllBooks();
            if (bookList != null)
            {
                _logger.LogInformation(LoggerMessageDisplay.BooksListed);
            }
            else
            {
                _logger.LogInformation(LoggerMessageDisplay.NoBooksInDB);
            }
            return View(bookList);
        }

        [HttpGet]
        public JsonResult FillBooksDataTable()
        {
            var booklist = _bookService.GetAllBooks();
            return Json(new { data = booklist });
        }

        // GET: Books/Details/5
        public IActionResult Details(int id)
        {
            var book = _bookService.GetBookById(id);
            _logger.LogInformation(LoggerMessageDisplay.BookFoundDisplayDetails);

            if (book == null)
            {
                _logger.LogWarning(LoggerMessageDisplay.NoBookFound);
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Details/5
        public JsonResult DetailBookDataTable(int id)
        {
            var book = _bookService.GetBookById(id);
            _logger.LogInformation(LoggerMessageDisplay.BookFoundDisplayDetails);

            if (book == null)
            {
                _logger.LogWarning(LoggerMessageDisplay.NoBookFound);
                throw new ArgumentNullException("NoBookFound");
            }

            return Json(new { detailsData = book });
        }

        // GET: Books/Create
        [Authorize(Roles = "admin")]    
        public IActionResult Create()
        {
            var Categories = _categoryService.GetCategories();
            var Authors = _authorService.GetAuthors();
            var Publishers = _publisherService.GetPublishers();

            BookViewModel bookViewModel = new BookViewModel
            {
                Categories = GetSelectListItemsCategory(Categories),
                Authors = GetSelectListAuthors(Authors),
                Publishers = GetSelectListPublishers(Publishers)
            };

            return View(bookViewModel);
        }

        private IEnumerable<SelectListItem> GetSelectListItemsCategory(IEnumerable<Category> categories)
        {
            var selectList = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Value = "0",
                    Text = "Select category..."
                }
            };
            foreach (var element in categories)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id.ToString(),
                    Text = element.Name
                });
            }
            return selectList;
        }

        private IEnumerable<SelectListItem> GetSelectListAuthors(IEnumerable<Author> authors)
        {
            var selectList = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Value = "0",
                    Text = "Select author..."
                }
            };
            foreach (var element in authors)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id.ToString(),
                    Text = element.Name
                });
            }
            return selectList;
        }

        private IEnumerable<SelectListItem> GetSelectListPublishers(IEnumerable<Publisher> publishers)
        {
            var selectList = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Value = "0",
                    Text = "Select publisher..."
                }
            };
            foreach (var element in publishers)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id.ToString(),
                    Text = element.Name
                });
            }
            return selectList;
        }


        // Generic Function
        //private IEnumerable<SelectListItem> GetSelectListGeneric(IEnumerable<T> publishers)
        //{
        //    var selectList = new List<SelectListItem>();
        //    selectList.Add(new SelectListItem
        //    {
        //        Value = "0",
        //        Text = "Select category..."
        //    });
        //    foreach (var element in publishers)
        //    {
        //        Type t = element.GetType();

        //        PropertyInfo prop = t.GetProperty("Items");

        //        object list = prop.GetValue(obj);

        //        selectList.Add(new SelectListItem
        //        {
        //            Value = element.Id.ToString(),
        //            Text = element.Name
        //        }); ;
        //    }
        //    return selectList;
        //}


        // POST: Books/Create
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookViewModel bookViewModel)
        {
            var book = new Book();

            if (ModelState.IsValid)
            {
                book.BookType = bookViewModel.BookType;
                book.CategoryID = bookViewModel.CategoryID;
                book.CategoryName = bookViewModel.CategoryName;
                book.Copies = bookViewModel.Copies;
                book.Country = bookViewModel.Country;
                book.Description = bookViewModel.Description;
                book.Dimensions = bookViewModel.Dimensions;
                book.Edition = bookViewModel.Edition;
                book.Genre = bookViewModel.Genre;
                book.Language = bookViewModel.Language;
                book.NumberOfPages = bookViewModel.NumberOfPages;
                book.Price = bookViewModel.Price;
                book.Shipping = bookViewModel.Shipping;
                book.Title = bookViewModel.Title;
                book.Weight = bookViewModel.Weight;
                book.YearOfIssue = bookViewModel.YearOfIssue;
                book.UserId = bookViewModel.UserId;
                book.PublisherID = bookViewModel.PublisherID;
                book.PublisherName = bookViewModel.PublisherName;
                book.AuthorID = bookViewModel.AuthorID;
                book.AuthorName = bookViewModel.AuthorName;
                book.PhotoURL = bookViewModel.PhotoURL;

                _bookService.AddBook(book);
                _logger.LogInformation(LoggerMessageDisplay.BookCreated);
                return RedirectToAction(nameof(Index));
            }
            _logger.LogError(LoggerMessageDisplay.BookNotCreatedModelStateInvalid);
            return View(book);
        }


        [HttpPost]
        public IActionResult UploadPhoto()
        {
            try
            {
                var file = Request.Form.Files[0];
                var folderName = Path.Combine("wwwroot", "images");
                var pathToSave = Path.Combine(Directory.GetCurrentDirectory(), folderName);

                if (file.Length > 0)
                {
                    var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    var fullPath = Path.Combine(pathToSave, fileName);
                    //var dbPath = Path.Combine(folderName, fileName);
                    var dbPath = fileName;

                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    _logger.LogInformation(LoggerMessageDisplay.PhotoUploaded);
                    return Ok(new { dbPath });
                }
                else
                {
                    _logger.LogError(LoggerMessageDisplay.PhotoUploadedError);
                    return BadRequest();
                }
            }
            catch (System.Exception ex)
            {
                _logger.LogError(LoggerMessageDisplay.PhotoUploadedError + " --->" + ex);
                return StatusCode(500, "Internal server error");
            }
        }

        // GET: Books/Edit/5
        public IActionResult Edit(int id)
        {
            var book = _bookService.GetBookById(id);

            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        [HttpPost]

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Areas.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookStore.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Controller
    {
        private UserManager<IdentityUser> _userManager;
        private IPasswordHasher<IdentityUser> _passwordHasher;
        private RoleManager<IdentityRole> _roleManager;

        public UserController(
            UserManager<IdentityUser> userManager,
            IPasswordHasher<IdentityUser> passwordHasher,
            RoleManager<IdentityRole> roleManager
            )
        {
            _userManager = userManager;
            _passwordHasher = passwordHasher;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var users = _userManager.Users;
            return View(users);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var roles = _roleManager.Roles;
            var userModel = new UserModel();
            userModel.Roles = GetSelectListRoles(roles);
            return View(userModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserModel user)
        {
            if (ModelState.IsValid)
            {
                IdentityUser appUser = new IdentityUser
                {
                    UserName = user.Name,
                    Email = user.Email,
                    EmailConfirmed = true
                };

                // istoto sto i gore 
                //IdentityUser appUser = new IdentityUser();
                //appUser.UserName = user.Name;
                //appUser.Email = user.Email;
                //appUser.EmailConfirmed = true;

                IdentityResult result = await _userManager.CreateAsync(appUser, user.Password);

                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(appUser, user.RoleName);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
                }
            }
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            var roles = _roleManager.Roles;

            if (user != null)
            {
                var getUserRole = await _userManager.GetRolesAsync(user);
                var userModel = new UserModel()
                {
                    Id = user.Id,
                    Email = user.Email,
                    Roles = GetSelectListRoles(roles)
                };
                return View(userModel);
            }
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, string email, string password, string RoleName)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var GetUserOldRole = _roleManager.FindByNameAsync(userRoles[0]);

                if (!string.IsNullOrEmpty(email))
                    user.Email = email;
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                if (!string.IsNullOrEmpty(password))
                    user.PasswordHash = _passwordHasher.HashPassword(user, password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(password))
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        await _userManager.RemoveFromRoleAsync(user, GetUserOldRole.Result.Name);
                        await _userManager.AddToRoleAsync(user, RoleName);
                        return RedirectToAction("Index");
                    }
                    else
                        Errors(result);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View("Index", _userManager.Users);
        }


        #region Helpers

        private IQueryable<SelectListItem> GetSelectListRoles(IQueryable<IdentityRole> roles)
        {
            var selectList = new List<SelectListItem>();
            selectList.Add(new SelectListItem
            {
                Value = "0",
                Text = "Select role..."
            });
            foreach (var element in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id,
                    Text = element.Name
                });
            }
            return selectList.AsQueryable();
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        #endregion


    }
}

Views/Shared/Notifications.cshtml
<span class="badge badge-danger"> @ViewData["Counter"]</span>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- CSS -->
    <script src="~/lib/font-awesome/css/all.css"></script>
    <link href="~/noty/noty.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    @*<environment include="Development"></environment>*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid ml-5 mr-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (ViewContext.HttpContext.User.IsInRole("admin") || ViewContext.HttpContext.User.IsInRole("editor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publishers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- js -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/js/form-validation.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


    <script src="~/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/datatables/js/dataTables.bootstrap4.min.js"></script>

    <script src="~/moment.js/moment.min.js"></script>

    <script src="~/noty/noty.js"></script>

    <!-- custom js scripts -->
    <script src="~/js/site.js" asp-append-version="true"></script>


    <!-- environments setup -->
    <!--<environment include="Development"></environment> -->

    @RenderSection("Scripts", required: false)
</body>
</html>